import {mkdirSync,existsSync,readFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {context} from '../../packages/robot-black-box-cli/src/index.mjs';
import {Recorder,localKey,atomicWrite} from '../../packages/robot-black-box-recorder/src/index.mjs';
import {TrustLifecycle} from '../../packages/robot-black-box-recorder/src/trust-lifecycle.mjs';
import {AssuranceService} from '../../packages/robot-black-box-recorder/src/assurance.mjs';
import {syntheticHandover} from '../../packages/robot-black-box-adapters/src/index.mjs';
import {canonical,digest,signed} from '../../packages/robot-black-box-contract/src/index.mjs';
import {verifyBundle} from '../../packages/robot-black-box-verifier/src/index.mjs';
import {evaluate,DEFAULT_POLICY} from '../../packages/robot-black-box-policy/src/index.mjs';
import {reportBytes,DurableReportStore} from '../../packages/robot-black-box-grc-bridge/src/durable.mjs';
const root=resolve(process.argv[2]??'.rbb/assurance-executed');if(existsSync(root))throw Error('OUTPUT_EXISTS');mkdirSync(root,{recursive:true,mode:0o700});const ctx=context(join(root,'custody')),lifecycle=new TrustLifecycle(join(root,'trust.sqlite'),ctx.authority),report={schema:'rbb.operational.execution.v1',started_at:new Date().toISOString(),scope:'finite scheduled checks of benign synthetic replay; no live sensor freshness',workers:[],decisions:[],durable:[],limitations:['Same-machine development authority/producer/witness and local SQLite custody; no remote endorsement or enterprise identity.','Current local verify time is distinct from old synthetic observation time; online source freshness unknown.','Rotation starts a new run epoch; historical snapshot verification never overrides current revocation.','Local SQLite WAL/FULL acknowledgement is not replicated disaster recovery or physical erasure.']};
const source=syntheticHandover({case_id:'H0',run_id:'operational-old',authority:ctx.authority,producer_id:ctx.producer.keyId});
function config(key,run_id,service_dir,objects=source.objects){atomicWrite(join(root,'config.json'),canonical({key_id:key.keyId,run_id,service_dir,interval_ms:40,artifacts:Object.fromEntries(Object.entries(objects).map(([id,b])=>[id,Buffer.from(b).toString('base64')]))}));}
function append(key,run_id,dir,events){const recorder=new Recorder({path:join(root,dir,'events.sqlite'),key,run_id,witness:ctx.witness});try{for(const e of events)recorder.append(e);}finally{recorder.close();}}
function worker(ticks=2,fault=false){const r=spawnSync(process.execPath,['scripts/robot-black-box/assurance-worker.mjs',root,String(ticks),...(fault?['fault']:[])],{encoding:'utf8',timeout:15000,maxBuffer:2*1024*1024});if(r.status!==0)throw Error('ASSURANCE_WORKER_FAILED:'+r.stderr);const result=JSON.parse(r.stdout);report.workers.push(result);return result;}
function denied(name,fn){try{fn();throw Error('EXPECTED_DENIAL_MISSING');}catch(e){if(e.message==='EXPECTED_DENIAL_MISSING')throw e;report.decisions.push({case:name,error:e.message});}}
try{
 const revision1=lifecycle.publish(ctx.trust);config(ctx.producer,'operational-old','old-service');append(ctx.producer,'operational-old','old-service',source.events.slice(0,2));const partial=worker();if(partial.results.some(r=>r.status!=='incomplete'))throw Error('PARTIAL_NOT_REPORTED');
 append(ctx.producer,'operational-old','old-service',source.events.slice(2));const failed=worker(1,true);if(failed.results[0].error!=='INJECTED_CHECKPOINT_PERSISTENCE_FAILURE'||failed.results[0].checkpoint_persisted)throw Error('CHECKPOINT_FAILURE_NOT_REPORTED');const recovered=worker();if(recovered.results.some(r=>r.status!=='locally_verified_replay'))throw Error('CHECKPOINT_RECOVERY_FAILED');
 const previous_checkpoint=ctx.witness.snapshot()['operational-old'];const next=localKey(join(root,'custody/producer-keys'),'producer-rotated'),trust2=structuredClone(ctx.trust);trust2.producers[next.keyId]={...trust2.producers[ctx.producer.keyId],public_key:next.public_key};
 const rotationBody={schema:'rbb.key.rotation.v1',old_key:ctx.producer.keyId,new_key:next.keyId,new_public_digest:digest(next.public_key),previous_run_id:'operational-old',previous_head_digest:previous_checkpoint.head_digest,mode:'new_run_epoch'};
 const revision2=lifecycle.publish(trust2,{rotation:{old:signed(rotationBody,ctx.producer.keyId,ctx.producer.privateKey,'KEY-ROTATION'),next:signed(rotationBody,next.keyId,next.privateKey,'KEY-ROTATION'),previous_checkpoint}});ctx.witness.producerKeys=trust2.producers;
 const rotatedSource=syntheticHandover({case_id:'H0',run_id:'operational-new',authority:ctx.authority,producer_id:next.keyId});config(next,'operational-new','new-service',rotatedSource.objects);append(next,'operational-new','new-service',rotatedSource.events);const rotated=worker();if(rotated.results.some(r=>r.verification.integrity!=='valid'))throw Error('ROTATION_VERIFICATION_FAILED');
 const oldPath=recovered.results.at(-1).verification.bundle_path,newPath=rotated.results.at(-1).verification.bundle_path;
 const revoked=structuredClone(trust2);revoked.producers[ctx.producer.keyId].revoked=true;lifecycle.publish(revoked);report.offline_history={historical:verifyBundle(oldPath,lifecycle.read(1,{historical:true}).trust,{latestHeads:ctx.witness.snapshot()}).integrity,current_revoked:verifyBundle(oldPath,revoked,{latestHeads:ctx.witness.snapshot()}).integrity,new_epoch:verifyBundle(newPath,revoked,{latestHeads:ctx.witness.snapshot()}).integrity};
 config(ctx.producer,'operational-old','old-service');const revokedWorker=worker(1);if(revokedWorker.results[0].error!=='PRODUCER_NOT_CURRENT')throw Error('REVOCATION_NOT_ENFORCED');const authorityRevoked=structuredClone(revoked);authorityRevoked.authorities[ctx.authority.keyId].revoked=true;lifecycle.publish(authorityRevoked);config(next,'operational-new','new-service',rotatedSource.objects);const staleAuthority=worker(1);if(staleAuthority.results[0].error!=='AUTHORITY_REVOKED')throw Error('AUTHORITY_REVOCATION_NOT_ENFORCED');
 lifecycle.publish(revoked);const service=new AssuranceService(join(root,'new-service'),{key:next,witness:ctx.witness,trustLifecycle:lifecycle,run_id:'operational-new',interval_ms:40});report.freshness={current:service.status(),aged:service.status({at:Date.now()+10000}),trust_aged:lifecycle.read(null,{at:Date.now()+120000}).freshness};service.close();
 const verification=verifyBundle(newPath,revoked,{latestHeads:ctx.witness.snapshot()}),content=reportBytes(verification,evaluate(verification,DEFAULT_POLICY,revoked)),actor={tenant:'tenant-a',role:'admin',subject:'demo-admin',purpose:'handover_evaluation'},request={actor,report:{id:'operational-new',purpose:actor.purpose,content,expected_digest:digest(content)}};atomicWrite(join(root,'durable-request.json'),canonical(request));
 const crashed=spawnSync(process.execPath,['scripts/robot-black-box/durable-worker.mjs',root,'crash'],{input:canonical(request),encoding:'utf8',timeout:15000});if(crashed.status!==99)throw Error('DURABLE_CRASH_NOT_EXECUTED');report.durable_crash_exit=crashed.status;
 for(let i=0;i<2;i++){const r=spawnSync(process.execPath,['scripts/robot-black-box/durable-worker.mjs',root],{input:canonical(request),encoding:'utf8',timeout:15000});if(r.status!==0)throw Error('DURABLE_RECONNECT_FAILED');report.durable.push(JSON.parse(r.stdout));}
 const store=new DurableReportStore(join(root,'durable-grc.sqlite'),localKey(join(root,'durable-custody'),'durable-local'));
 try{denied('mismatched_digest',()=>store.attach(actor,{...request.report,expected_digest:'0'.repeat(64)}));denied('cross_tenant_read',()=>store.read({...actor,tenant:'tenant-b'},request.report.id,actor.purpose));denied('wrong_purpose_read',()=>store.read({...actor,purpose:'governance_evaluation'},request.report.id,actor.purpose));store.hold(actor,request.report.id,actor.purpose,true);denied('held_report_removal',()=>store.remove(actor,request.report.id,actor.purpose));report.durable_readback=store.reconcile(actor,request.report.id,actor.purpose,request.report.expected_digest);}finally{store.close();}
 report.trust_revisions=[revision1,revision2,lifecycle.latest()];report.status='verified_finite_local_assurance';report.completed_at=new Date().toISOString();atomicWrite(join(root,'execution.json'),canonical(report));atomicWrite(join(root,'trust-public.json'),canonical(lifecycle.latest().trust));atomicWrite(join(root,'heads-public.json'),canonical(ctx.witness.snapshot()));console.log(JSON.stringify({status:report.status,worker_processes:report.workers.length,checks:report.workers.reduce((n,w)=>n+w.results.length,0),history:report.offline_history,durable_digest:request.report.expected_digest}));
}finally{lifecycle.close();ctx.witness.close();}
