import {existsSync,readFileSync,writeFileSync,rmSync,cpSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {performance} from 'node:perf_hooks';
import {custodyDemo,workerConfig} from './custody-demo-context.mjs';
import {canonical,digest} from '../../packages/robot-black-box-contract/src/index.mjs';
const root=resolve(process.argv[2]??'.rbb/custody-backup-executed');if(existsSync(root))throw Error('EXECUTION_ROOT_MUST_BE_NEW');const x=custodyDemo(root),steps=[],worker=resolve('scripts/robot-black-box/custody-backup.mjs');
const run=(name,payload,status=0,tool=worker)=>{const path=join(root,name+'.json');writeFileSync(path,canonical(payload),{mode:0o600});const start=performance.now(),r=spawnSync(process.execPath,[tool,path],{encoding:'utf8'});if(r.status!==status)throw Error(name+':'+r.stderr);const result=status===0?JSON.parse(r.stdout):null;steps.push({name,pid:r.pid,status:r.status,elapsed_ms:performance.now()-start,result,error:r.stderr.split('\n').filter(s=>!s.startsWith('(node:')&&!s.startsWith('(Use ')).join('\n')});return result;};
run('acceptance',{...x.config,operation:'accept',request:x.request},0,resolve('scripts/robot-black-box/local-custody.mjs'));
const backup={directory:join(root,'backup'),backupId:'store-loss-backup-001',acceptanceId:x.base.acceptance_id,...x.reviewer};run('backup_interruption',{operation:'backup',config:x.config,request:{...backup,fault:'before_seal'}},97);const sealed=run('backup_retry',{operation:'backup',config:x.config,request:backup});if(!run('backup_idempotent',{operation:'backup',config:x.config,request:backup}).idempotent)throw Error('BACKUP_CHANGED');
const isolated=join(root,'isolated-backup');cpSync(backup.directory,isolated,{recursive:true});rmSync(backup.directory,{recursive:true});rmSync(x.request.packagePath,{recursive:true});for(const path of [x.config.path,x.config.path+'-wal',x.config.path+'-shm'])if(existsSync(path))rmSync(path);for(const name of ['acceptance','backup_interruption','backup_retry','backup_idempotent'])rmSync(join(root,name+'.json'));
const request={directory:isolated,output:join(root,'recovery'),keys:x.custodianKeys,expectedReceiptDigest:sealed.receipt_digest,acceptanceId:x.base.acceptance_id,...x.reviewer};
for(const fault of ['database','receipt','missing']){const directory=join(root,'damaged-'+fault);cpSync(isolated,directory,{recursive:true});if(fault==='database')writeFileSync(join(directory,'backup.sqlite'),'corrupt');if(fault==='receipt')writeFileSync(join(directory,'receipt.json'),'{}');if(fault==='missing')rmSync(join(directory,'backup.sqlite'));run('reject_'+fault,{operation:'recover',request:{...request,directory,output:join(root,'denied-'+fault)}},2);}
run('reject_wrong_pin',{operation:'recover',request:{...request,expectedReceiptDigest:'0'.repeat(64),output:join(root,'denied-pin')}},2);
const recovered=run('recover_without_original_store',{operation:'recover',request});const trustedTool=join(root,'trusted-bootstrap.mjs');writeFileSync(trustedTool,readFileSync(resolve('scripts/robot-black-box/portable-bootstrap.mjs')),{mode:0o600});const start=performance.now(),review=spawnSync(process.execPath,[trustedTool,recovered.package_path,x.reviewer.manifestDigest],{encoding:'utf8'});if(review.status!==0)throw Error(review.stderr||review.stdout);const report=JSON.parse(review.stdout);if(report.review.cases.length!==6||report.review.cryptographic_integrity!=='valid')throw Error('BACKUP_REVIEW_FAILED');
const out=resolve('examples/robot-black-box-portable/executed');mkdirSync(out,{recursive:true});writeFileSync(join(out,'backup-receipt.json'),canonical(sealed.receipt));writeFileSync(join(out,'backup-public-trust.json'),canonical({custodians:x.custodianKeys,custodian_fingerprint:x.reviewer.expectedCustodianFingerprint,backup_receipt_digest:sealed.receipt_digest,pin_origin:'same_host_demo_not_independently_distributed'}));writeFileSync(join(out,'backup-restored-review.json'),canonical(report));writeFileSync(join(out,'backup-recovery-execution.json'),canonical({schema:'rbb.custody.backup.recovery.execution.v1',at:new Date().toISOString(),controller_pid:process.pid,steps,bootstrap_pid:review.pid,bootstrap_elapsed_ms:performance.now()-start,trusted_bootstrap_sha256:digest(readFileSync(trustedTool)),original_store_removed_before_recovery:!existsSync(x.config.path),assembly_removed_before_recovery:!existsSync(x.request.packagePath),original_backup_removed_before_recovery:true,private_worker_configs_removed:true,recovery_worker_private_key:false,backup_receipt_digest:sealed.receipt_digest,restored_files:recovered.restored_files,cases:6,scope:'isolated same-host directory backup; externally distributed trust/off-host replication not executed; timings observational not production RTO/RPO'}));console.log('Signed isolated backup recovered 47 files/six cases after source database, assembly and private worker configs were removed.');
