import {readFileSync,writeFileSync,mkdirSync,existsSync,rmSync,cpSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {custodyDemo,workerConfig} from './custody-demo-context.mjs';
import {verifyAcceptance} from './local-custody.mjs';
import {canonical,digest,signed} from '../../packages/robot-black-box-contract/src/index.mjs';
const root=resolve(process.argv[2]??'.rbb/custody-restore-executed');if(existsSync(root))throw Error('EXECUTION_ROOT_MUST_BE_NEW');const x=custodyDemo(root),worker=resolve('scripts/robot-black-box/local-custody.mjs'),steps=[];
const run=(name,config,operation,request,expected=0)=>{const path=workerConfig(join(root,name+'.json'),config,operation,request),r=spawnSync(process.execPath,[worker,path],{encoding:'utf8'});if(r.status!==expected)throw Error(name+':'+r.stderr);const value=r.status===0?JSON.parse(r.stdout):null;steps.push({name,pid:r.pid,exit_status:r.status,result:value,error:r.stderr.split('\n').filter(s=>!s.startsWith('(node:')&&!s.startsWith('(Use ')).join('\n')});return value;};
run('interrupted_before_commit',x.config,'accept',{...x.request,fault:'before_commit'},99);const acceptance=run('retry_acceptance',x.config,'accept',x.request);if(acceptance.idempotent)throw Error('ROLLBACK_NOT_RECOVERED');const repeat=run('idempotent_acceptance',x.config,'accept',x.request);if(!repeat.idempotent||canonical(repeat.receipt)!==canonical(acceptance.receipt))throw Error('ACCEPTANCE_CHANGED');
const secondGrant=signed({...x.base,acceptance_id:'acceptance-public-lost-ack'},x.issuer.keyId,x.issuer.privateKey,'CUSTODY-GRANT');run('interrupted_after_commit',x.config,'accept',{...x.request,grant:secondGrant,fault:'after_commit'},98);if(!run('retry_lost_ack',x.config,'accept',{...x.request,grant:secondGrant}).idempotent)throw Error('LOST_ACK_RECOVERY');
rmSync(x.request.packagePath,{recursive:true});const publicConfig={path:x.config.path,key:null,authorityKeys:{},custodianKeys:x.custodianKeys},restore={acceptanceId:x.base.acceptance_id,output:join(root,'restored'),...x.reviewer};run('wrong_identity',publicConfig,'restore',{...restore,expectedCustodianFingerprint:'0'.repeat(64),output:join(root,'denied-wrong-identity')},2);
// Copies of a closed WAL-checkpointed store are used for destructive fault rehearsal, never the accepted original.
for(const fault of ['bytes','missing','receipt']){const path=join(root,'tampered-'+fault+'.sqlite');cpSync(x.config.path,path);const db=new DatabaseSync(path);if(fault==='bytes')db.prepare('UPDATE files SET bytes=? WHERE id=? AND path=?').run(Buffer.from('tampered'),x.base.acceptance_id,'README.md');if(fault==='missing')db.prepare('DELETE FROM files WHERE id=? AND path=?').run(x.base.acceptance_id,'README.md');if(fault==='receipt'){const r=JSON.parse(db.prepare('SELECT receipt FROM acceptances WHERE id=?').get(x.base.acceptance_id).receipt);r.purpose='forged';db.prepare('UPDATE acceptances SET receipt=? WHERE id=?').run(canonical(r),x.base.acceptance_id);}db.close();run('tampered_'+fault,{...publicConfig,path},'restore',{...restore,output:join(root,'denied-'+fault)},2);}
const restored=run('clean_restore',publicConfig,'restore',restore);verifyAcceptance(restored.receipt,{keys:x.custodianKeys,...x.reviewer});const trustedTool=join(root,'reviewer-owned-bootstrap.mjs');writeFileSync(trustedTool,readFileSync(resolve('scripts/robot-black-box/portable-bootstrap.mjs')),{mode:0o600});const verification=spawnSync(process.execPath,[trustedTool,restore.output,x.reviewer.manifestDigest],{encoding:'utf8'});if(verification.status!==0)throw Error(verification.stderr||verification.stdout);const reviewed=JSON.parse(verification.stdout);if(reviewed.review.cryptographic_integrity!=='valid'||reviewed.review.cases.length!==6)throw Error('RESTORED_REVIEW_FAILED');
const out=resolve('examples/robot-black-box-portable/executed');mkdirSync(out,{recursive:true});writeFileSync(join(out,'custody-acceptance.json'),canonical(acceptance.receipt));writeFileSync(join(out,'custody-grant.json'),canonical(x.grant));writeFileSync(join(out,'custody-public-trust.json'),canonical({authorities:x.config.authorityKeys,custodians:x.custodianKeys,demonstration_pin:x.reviewer.expectedCustodianFingerprint,pin_origin:'same_host_demo_generated_not_independent_distribution'}));writeFileSync(join(out,'custody-restored-review.json'),canonical(reviewed));
const execution={schema:'rbb.custody.restore.execution.v1',at:new Date().toISOString(),controller_pid:process.pid,steps,restore_receipt_verified:true,bootstrap_pid:verification.pid,source_assembly_removed_before_restore:true,restore_worker_received_private_key:false,original_public_fixture_preserved:true,restored_files:restored.restored_files,evidence_cases:6,custodian_fingerprint:x.reviewer.expectedCustodianFingerprint,trusted_bootstrap_sha256:digest(readFileSync(trustedTool)),manifest_digest:x.reviewer.manifestDigest,inventory_digest:acceptance.receipt.inventory_digest,receipt_sha256:digest(canonical(acceptance.receipt)),trust_origin:'all_demo_keys_and_pins_generated_same_host_not_organizationally_independent',limits:'local SQLite logical immutability/recovery only; no cloud/replication/HSM/hardware survival/live source truth/legal admissibility/independent custody'};writeFileSync(join(out,'custody-restore-execution.json'),canonical(execution));console.log('Local custody accepted, interrupted/retried, rejected four damaged/identity cases, restored 47 files and verified six signed cases.');
