import {existsSync,mkdirSync,writeFileSync,readFileSync,mkdtempSync,rmSync,readdirSync,lstatSync,openSync,fsyncSync,closeSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {canonical,digest,signed,authenticate,exact} from '../../packages/robot-black-box-contract/src/index.mjs';
import {atomicWrite} from '../../packages/robot-black-box-recorder/src/index.mjs';
import {LocalCustody,verifyAcceptance,CUSTODY_SCOPE} from './local-custody.mjs';
import {boundedRead} from './portable-bootstrap.mjs';
const hex=s=>typeof s==='string'&&/^[a-f0-9]{64}$/.test(s);
function envelope(receipt,keys,pin,domain){if(!hex(pin))throw Error('CUSTODIAN_PIN_REQUIRED');const key=keys[receipt.authentication?.key_id];if(!key||digest(key.public_key)!==pin)throw Error('CUSTODIAN_IDENTITY_PIN_MISMATCH');const b=authenticate(receipt,keys,domain);if(!key.tenants?.includes(b.tenant)||!key.purposes?.includes(b.purpose)||b.scope!==CUSTODY_SCOPE)throw Error('BACKUP_SCOPE');return b;}
function directory(path,allowed){if(lstatSync(path).isSymbolicLink()||!lstatSync(path).isDirectory())throw Error('UNSAFE_BACKUP_DIRECTORY');for(const p of readdirSync(path))if(!allowed.includes(p))throw Error('UNEXPECTED_BACKUP_FILE');}
export function verifyBackup({directory:path,keys,expectedCustodianFingerprint,expectedReceiptDigest,tenant,purpose,acceptanceId,manifestDigest}){
 if(!hex(expectedReceiptDigest))throw Error('BACKUP_RECEIPT_PIN_REQUIRED');directory(path,['intent.json','backup.sqlite','receipt.json']);const receiptBytes=boundedRead(join(path,'receipt.json'));if(digest(receiptBytes)!==expectedReceiptDigest)throw Error('BACKUP_RECEIPT_PIN_MISMATCH');const receipt=JSON.parse(receiptBytes),body=envelope(receipt,keys,expectedCustodianFingerprint,'CUSTODY-BACKUP');exact(body,['schema','backup_id','issuer','tenant','purpose','scope','acceptance_id','acceptance_receipt_digest','manifest_digest','created_at','database_digest','database_bytes','intent_digest'],'BACKUP');if(body.schema!=='rbb.custody.backup.v1'||body.issuer!==receipt.authentication.key_id||body.tenant!==tenant||body.purpose!==purpose||body.acceptance_id!==acceptanceId||body.manifest_digest!==manifestDigest||!Number.isFinite(Date.parse(body.created_at)))throw Error('BACKUP_SCOPE');const intentBytes=boundedRead(join(path,'intent.json'));if(digest(intentBytes)!==body.intent_digest)throw Error('BACKUP_INTENT_CHANGED');const bytes=boundedRead(join(path,'backup.sqlite'));if(bytes.length!==body.database_bytes||digest(bytes)!==body.database_digest)throw Error('BACKUP_DATABASE_CHANGED');return {receipt,body,bytes};
}
export function createBackup(config,{directory:path,backupId,acceptanceId,fault=null,...reviewer}){
 if(!/^[A-Za-z0-9_-]{1,80}$/.test(backupId))throw Error('BACKUP_ID');const store=new LocalCustody(config);let validation;
 try{validation=mkdtempSync(join(tmpdir(),'rbb-backup-validation-'));const accepted=store.restore({acceptanceId,output:join(validation,'package'),...reviewer}),body=verifyAcceptance(accepted.receipt,{keys:config.custodianKeys,...reviewer});const intentBody={schema:'rbb.custody.backup.intent.v1',backup_id:backupId,issuer:config.key.keyId,tenant:body.tenant,purpose:body.purpose,scope:CUSTODY_SCOPE,acceptance_id:acceptanceId,acceptance_receipt_digest:digest(canonical(accepted.receipt)),manifest_digest:body.manifest_digest};
 if(!existsSync(path)){mkdirSync(path,{recursive:true,mode:0o700});atomicWrite(join(path,'intent.json'),canonical(signed(intentBody,config.key.keyId,config.key.privateKey,'CUSTODY-BACKUP-INTENT')));}directory(path,['intent.json','backup.sqlite','receipt.json']);const intentBytes=boundedRead(join(path,'intent.json')),intent=JSON.parse(intentBytes);if(canonical(envelope(intent,config.custodianKeys,reviewer.expectedCustodianFingerprint,'CUSTODY-BACKUP-INTENT'))!==canonical(intentBody))throw Error('BACKUP_ID_CONFLICT');
 if(existsSync(join(path,'receipt.json'))){const expectedReceiptDigest=digest(boundedRead(join(path,'receipt.json')));const prior=verifyBackup({directory:path,keys:config.custodianKeys,...reviewer,acceptanceId,expectedReceiptDigest});return {receipt:prior.receipt,receipt_digest:expectedReceiptDigest,idempotent:true};}
 const databasePath=join(path,'backup.sqlite');if(!existsSync(databasePath))store.db.prepare('VACUUM INTO ?').run(databasePath);const bytes=boundedRead(databasePath);const fd=openSync(databasePath,'r');try{fsyncSync(fd);}finally{closeSync(fd);}if(fault==='before_seal')process.exit(97);
 // Re-validate the snapshot's selected acceptance and package before sealing resumed output.
 const snapshot=new LocalCustody({...config,path:databasePath,key:null});try{const readback=snapshot.restore({acceptanceId,output:join(validation,'snapshot-package'),...reviewer});if(canonical(readback.receipt)!==canonical(accepted.receipt))throw Error('BACKUP_ACCEPTANCE_CHANGED');}finally{snapshot.close();}
 const finalBytes=boundedRead(databasePath),receipt=signed({...intentBody,schema:'rbb.custody.backup.v1',created_at:new Date().toISOString(),database_digest:digest(finalBytes),database_bytes:finalBytes.length,intent_digest:digest(intentBytes)},config.key.keyId,config.key.privateKey,'CUSTODY-BACKUP');atomicWrite(join(path,'receipt.json'),canonical(receipt));return {receipt,receipt_digest:digest(canonical(receipt)),idempotent:false};
 }finally{store.close();if(validation)rmSync(validation,{recursive:true,force:true});}
}
export function recoverBackup({directory:path,output,...reviewer}){
 if(existsSync(output))throw Error('RECOVERY_OUTPUT_MUST_BE_NEW');const verified=verifyBackup({directory:path,...reviewer});mkdirSync(output,{recursive:true,mode:0o700});const dbPath=join(output,'recovered-custody.sqlite');atomicWrite(dbPath,verified.bytes);const store=new LocalCustody({path:dbPath,key:null,authorityKeys:{},custodianKeys:reviewer.keys});try{const restored=store.restore({acceptanceId:reviewer.acceptanceId,output:join(output,'package'),...reviewer});if(digest(canonical(restored.receipt))!==verified.body.acceptance_receipt_digest)throw Error('RECOVERY_ACCEPTANCE_CHANGED');return {backup_receipt_verified:true,acceptance_receipt_verified:true,restored_files:restored.restored_files,package_path:join(output,'package'),receipt:restored.receipt,private_key_required:false};}catch(e){rmSync(output,{recursive:true,force:true});throw e;}finally{store.close();}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const c=JSON.parse(readFileSync(process.argv[2]));console.log(JSON.stringify(c.operation==='backup'?createBackup(c.config,c.request):recoverBackup(c.request)));}catch(e){console.error(e.message);process.exitCode=2;}}
