import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,writeFileSync,existsSync,readFileSync} from 'node:fs';
import {join,dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {canonical,digest,signed,authenticate,exact} from '../../packages/robot-black-box-contract/src/index.mjs';
import {checkedPackage} from './portable-bootstrap.mjs';
export const CUSTODY_SCOPE='public_synthetic_portable_package_local_only';
export const PUBLIC_PACKAGE_DIGEST=digest(readFileSync(new URL('../../examples/robot-black-box-portable/executed/review-package/package-manifest.json',import.meta.url)));
const hex=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
const id=x=>typeof x==='string'&&/^[A-Za-z0-9_-]{1,80}$/.test(x);
export function verifyAcceptance(receipt,{keys,expectedCustodianFingerprint,tenant,purpose,manifestDigest,inventoryDigest}){
 if(!hex(expectedCustodianFingerprint))throw Error('CUSTODIAN_PIN_REQUIRED');const key=keys[receipt.authentication?.key_id];if(!key||digest(key.public_key)!==expectedCustodianFingerprint)throw Error('CUSTODIAN_IDENTITY_PIN_MISMATCH');const body=authenticate(receipt,keys,'CUSTODY-ACCEPTANCE');
 exact(body,['schema','acceptance_id','issuer','tenant','purpose','scope','manifest_digest','inventory_digest','accepted_at','grant_digest','custody'],'CUSTODY_RECEIPT');
 if(body.schema!=='rbb.custody.acceptance.v1'||body.issuer!==receipt.authentication.key_id||!id(body.acceptance_id)||body.tenant!==tenant||body.purpose!==purpose||body.manifest_digest!==manifestDigest||(inventoryDigest&&body.inventory_digest!==inventoryDigest)||!hex(body.inventory_digest)||!hex(body.grant_digest)||!Number.isFinite(Date.parse(body.accepted_at))||body.scope!==CUSTODY_SCOPE||body.custody!=='separate_local_key_database_process_same_host'||!key.tenants?.includes(tenant)||!key.purposes?.includes(purpose))throw Error('CUSTODY_RECEIPT_SCOPE');return body;
}
export class LocalCustody {
 constructor({path,key,authorityKeys,custodianKeys}){mkdirSync(dirname(path),{recursive:true,mode:0o700});this.db=new DatabaseSync(path);this.db.exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS acceptances(id TEXT PRIMARY KEY, binding TEXT NOT NULL, receipt TEXT NOT NULL); CREATE TABLE IF NOT EXISTS files(id TEXT,path TEXT,bytes BLOB NOT NULL,PRIMARY KEY(id,path));');this.key=key;this.authorityKeys=authorityKeys;this.custodianKeys=custodianKeys;}
 accept({packagePath,manifestDigest,grant,fault=null}){
 if(manifestDigest!==PUBLIC_PACKAGE_DIGEST)throw Error('PUBLIC_PACKAGE_ONLY');
 const g=authenticate(grant,this.authorityKeys,'CUSTODY-GRANT');exact(g,['schema','issuer','acceptance_id','tenant','purpose','scope','manifest_digest','not_before','expires_at'],'CUSTODY_GRANT');const issuer=this.authorityKeys[grant.authentication.key_id],now=new Date().toISOString();if(g.schema!=='rbb.custody.grant.v1'||g.issuer!==grant.authentication.key_id||!id(g.acceptance_id)||g.scope!==CUSTODY_SCOPE||g.manifest_digest!==manifestDigest||!hex(manifestDigest)||!issuer.tenants?.includes(g.tenant)||!issuer.purposes?.includes(g.purpose)||!Number.isFinite(Date.parse(g.not_before))||!Number.isFinite(Date.parse(g.expires_at))||Date.parse(now)<Date.parse(g.not_before)||Date.parse(now)>Date.parse(g.expires_at))throw Error('CUSTODY_GRANT_SCOPE_OR_EXPIRY');
 const custodian=this.custodianKeys[this.key.keyId];if(!custodian||custodian.revoked||!custodian.tenants?.includes(g.tenant)||!custodian.purposes?.includes(g.purpose))throw Error('CUSTODIAN_NOT_ENROLLED');
 if(g.tenant!=='tenant-a'||g.purpose!=='investigation_review'||digest(issuer.public_key)===digest(custodian.public_key))throw Error('CUSTODY_ROLE_OR_SCOPE');
 const {bytes,manifestBytes}=checkedPackage(packagePath,manifestDigest);const publisherTrust=JSON.parse(bytes.get('evidence/trust.json').toString());for(const section of ['producers','authorities','witnesses'])for(const enrolled of Object.values(publisherTrust[section]??{}))if([custodian.public_key,issuer.public_key].includes(enrolled.public_key))throw Error('CUSTODY_ROLE_OR_SCOPE');const manifest=JSON.parse(manifestBytes),inventoryDigest=digest(canonical(manifest.files)),binding=canonical({grant_digest:digest(canonical(grant)),manifest_digest:manifestDigest,inventory_digest:inventoryDigest,tenant:g.tenant,purpose:g.purpose});
 this.db.exec('BEGIN IMMEDIATE');try{const prior=this.db.prepare('SELECT binding,receipt FROM acceptances WHERE id=?').get(g.acceptance_id);if(prior){if(prior.binding!==binding)throw Error('ACCEPTANCE_ID_CONFLICT');this.db.exec('COMMIT');return {receipt:JSON.parse(prior.receipt),idempotent:true};}
 const receipt=signed({schema:'rbb.custody.acceptance.v1',acceptance_id:g.acceptance_id,issuer:this.key.keyId,tenant:g.tenant,purpose:g.purpose,scope:CUSTODY_SCOPE,manifest_digest:manifestDigest,inventory_digest:inventoryDigest,accepted_at:now,grant_digest:digest(canonical(grant)),custody:'separate_local_key_database_process_same_host'},this.key.keyId,this.key.privateKey,'CUSTODY-ACCEPTANCE');
 verifyAcceptance(receipt,{keys:this.custodianKeys,expectedCustodianFingerprint:digest(custodian.public_key),tenant:g.tenant,purpose:g.purpose,manifestDigest,inventoryDigest});
 this.db.prepare('INSERT INTO acceptances VALUES(?,?,?)').run(g.acceptance_id,binding,canonical(receipt));bytes.set('package-manifest.json',manifestBytes);const insert=this.db.prepare('INSERT INTO files VALUES(?,?,?)');for(const [path,b] of bytes)insert.run(g.acceptance_id,path,b);if(fault==='before_commit')process.exit(99);this.db.exec('COMMIT');if(fault==='after_commit')process.exit(98);return {receipt,idempotent:false};
 }catch(e){this.db.exec('ROLLBACK');throw e;}
 }
 restore({acceptanceId,output,...reviewer}){
 if(!id(acceptanceId)||existsSync(output))throw Error('RESTORE_ID_OR_OUTPUT');const row=this.db.prepare('SELECT receipt FROM acceptances WHERE id=?').get(acceptanceId);if(!row)throw Error('ACCEPTANCE_NOT_FOUND');const receipt=JSON.parse(row.receipt);const body=verifyAcceptance(receipt,{keys:this.custodianKeys,...reviewer});if(body.acceptance_id!==acceptanceId)throw Error('CUSTODY_ID_MISMATCH');
 const rows=this.db.prepare('SELECT path,bytes FROM files WHERE id=? ORDER BY path').all(acceptanceId);if(rows.length>513)throw Error('INTAKE_LIMIT');let total=0;const manifestRow=rows.find(r=>r.path==='package-manifest.json');if(!manifestRow||digest(manifestRow.bytes)!==body.manifest_digest)throw Error('CUSTODY_PACKAGE_MISSING_OR_CHANGED');const manifest=JSON.parse(Buffer.from(manifestRow.bytes).toString());if(digest(canonical(manifest.files))!==body.inventory_digest)throw Error('CUSTODY_INVENTORY_CHANGED');
 const expected=new Map(manifest.files.map(f=>[f.path,f]));if(rows.length!==expected.size+1)throw Error('CUSTODY_PACKAGE_MISSING_OR_CHANGED');for(const r of rows){if(typeof r.path!=='string'||!/^([A-Za-z0-9_-]+\/)*[A-Za-z0-9_.-]+$/.test(r.path)||r.path.split('/').some(x=>x==='.'||x==='..')||r.path.split('/').length>16||r.bytes.length>16*1024*1024||(total+=r.bytes.length)>32*1024*1024)throw Error('CUSTODY_INTAKE_REJECTED');if(r.path!=='package-manifest.json'){const f=expected.get(r.path);if(!f||f.bytes!==r.bytes.length||f.sha256!==digest(r.bytes))throw Error('CUSTODY_PACKAGE_MISSING_OR_CHANGED');}}
 mkdirSync(output,{mode:0o700});for(const r of rows){const dest=join(output,r.path);mkdirSync(dirname(dest),{recursive:true,mode:0o700});writeFileSync(dest,r.bytes,{mode:0o600,flag:'wx'});}checkedPackage(output,body.manifest_digest);return {receipt,restored_files:rows.length,receipt_verified:true,scope:CUSTODY_SCOPE};
 }
 close(){this.db.close();}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const config=JSON.parse(readFileSync(process.argv[2])),store=new LocalCustody(config);try{console.log(JSON.stringify(store[config.operation](config.request)));}finally{store.close();}}catch(e){console.error(e.message);process.exitCode=2;}}
