import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {authenticate,canonical,digest,exact} from '../../packages/robot-black-box-contract/src/index.mjs';
import {recoverBackup} from './custody-backup.mjs';
export function recoveryTrust({records,authorityKeys,expectedAuthorityFingerprint,minimumRevision,tenant=null,purpose=null,at=Date.now()}){
 if(typeof expectedAuthorityFingerprint!=='string'||! /^[a-f0-9]{64}$/.test(expectedAuthorityFingerprint))throw Error('RECOVERY_AUTHORITY_PIN_REQUIRED');if(!Number.isSafeInteger(minimumRevision)||minimumRevision<1)throw Error('MINIMUM_TRUST_REVISION_REQUIRED');if(!Array.isArray(records)||records.length<1||records.length>128)throw Error('TRUST_CHAIN_LIMIT');let previous=null,latest=null;
 for(const record of records){const key=authorityKeys[record.authentication?.key_id];if(!key||digest(key.public_key)!==expectedAuthorityFingerprint)throw Error('RECOVERY_AUTHORITY_PIN_MISMATCH');if(tenant&&(!key.tenants?.includes(tenant)||!key.purposes?.includes(purpose)))throw Error('RECOVERY_AUTHORITY_SCOPE');const b=authenticate(record,authorityKeys,'TRUST-LIFECYCLE');exact(b,['schema','revision','previous_digest','issued_at','expires_at','trust','rotation','scope'],'RECOVERY_TRUST');if(b.schema!=='rbb.trust.lifecycle.v1'||b.revision!==(previous?.revision??0)+1||b.previous_digest!==(previous?digest(canonical(previous)):null)||b.rotation!==null||(previous&&Date.parse(b.issued_at)<Date.parse(previous.issued_at))||!Number.isFinite(Date.parse(b.issued_at))||!Number.isFinite(Date.parse(b.expires_at))||Date.parse(b.expires_at)<=Date.parse(b.issued_at))throw Error('RECOVERY_TRUST_CHAIN');previous=record;latest=b;}
 if(latest.revision<minimumRevision)throw Error('RECOVERY_TRUST_ROLLBACK');if(!Number.isFinite(at)||at<Date.parse(latest.issued_at)||at>=Date.parse(latest.expires_at))throw Error('RECOVERY_TRUST_STALE');if(!latest.trust.custodians||typeof latest.trust.custodians!=='object'||Array.isArray(latest.trust.custodians))throw Error('CUSTODIAN_ENROLLMENT_MISSING');return {keys:latest.trust.custodians,revision:latest.revision,trust_digest:digest(canonical(previous)),freshness:'valid_local_signed_snapshot_not_online_attested'};
}
export function recoverWithTrust({trust,request}){const enrolled=recoveryTrust({...trust,tenant:request.tenant,purpose:request.purpose,at:Date.now()});const recovered=recoverBackup({...request,keys:enrolled.keys});return {...recovered,recovery_trust_revision:enrolled.revision,recovery_trust_digest:enrolled.trust_digest,online_freshness:'unknown',trust_source:'reviewer_pinned_authority_signed_local_revision'};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{console.log(JSON.stringify(recoverWithTrust(JSON.parse(readFileSync(process.argv[2])))));}catch(e){console.error(e.message);process.exitCode=2;}}
