import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,existsSync,lstatSync,readFileSync,chmodSync} from 'node:fs';
import {dirname,resolve,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {canonical,digest,exact} from '../../packages/robot-black-box-contract/src/index.mjs';
import {recoveryTrust} from './recovery-trust.mjs';
import {recoverBackup} from './custody-backup.mjs';
export class ReviewerState {
 constructor(path){if(existsSync(path)){const s=lstatSync(path);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1)throw Error('UNSAFE_REVIEWER_STATE');}mkdirSync(dirname(path),{recursive:true,mode:0o700});this.path=resolve(path);this.db=new DatabaseSync(path);chmodSync(path,0o600);this.db.exec('PRAGMA busy_timeout=5000;PRAGMA journal_mode=WAL;PRAGMA synchronous=FULL;CREATE TABLE IF NOT EXISTS profiles(id TEXT PRIMARY KEY,anchors TEXT NOT NULL,revision INTEGER NOT NULL,digest TEXT);CREATE TABLE IF NOT EXISTS observations(profile TEXT,revision INTEGER,digest TEXT,observed_at TEXT,PRIMARY KEY(profile,revision));');}
 enroll(profile){exact(profile,['profile_id','authority_fingerprint','tenant','purpose','initial_minimum_revision'],'REVIEWER_PROFILE');if(!/^[A-Za-z0-9_-]{1,80}$/.test(profile.profile_id)||! /^[a-f0-9]{64}$/.test(profile.authority_fingerprint)||typeof profile.tenant!=='string'||typeof profile.purpose!=='string'||!Number.isSafeInteger(profile.initial_minimum_revision)||profile.initial_minimum_revision<1)throw Error('REVIEWER_PROFILE_INVALID');const anchors=canonical(profile);this.db.exec('BEGIN IMMEDIATE');try{const prior=this.db.prepare('SELECT anchors FROM profiles WHERE id=?').get(profile.profile_id);if(prior&&prior.anchors!==anchors)throw Error('REVIEWER_PROFILE_CONFLICT');if(!prior)this.db.prepare('INSERT INTO profiles VALUES(?,?,0,NULL)').run(profile.profile_id,anchors);this.db.exec('COMMIT');return {enrolled:true,idempotent:Boolean(prior)};}catch(e){this.db.exec('ROLLBACK');throw e;}}
 observe({profileId,trust,fault=null}){this.db.exec('BEGIN IMMEDIATE');try{const prior=this.db.prepare('SELECT * FROM profiles WHERE id=?').get(profileId);if(!prior)throw Error('REVIEWER_PROFILE_NOT_ENROLLED');const profile=JSON.parse(prior.anchors);if(trust.expectedAuthorityFingerprint!==profile.authority_fingerprint)throw Error('REVIEWER_AUTHORITY_CHANGED');const enrolled=recoveryTrust({...trust,expectedAuthorityFingerprint:profile.authority_fingerprint,minimumRevision:Math.max(prior.revision,profile.initial_minimum_revision),tenant:profile.tenant,purpose:profile.purpose,at:Date.now()});if(prior.revision){const ancestor=trust.records.find(r=>r.revision===prior.revision);if(!ancestor||digest(canonical(ancestor))!==prior.digest)throw Error('REVIEWER_TRUST_FORK');}const idempotent=prior.revision===enrolled.revision;if(!idempotent){this.db.prepare('UPDATE profiles SET revision=?,digest=? WHERE id=?').run(enrolled.revision,enrolled.trust_digest,profileId);this.db.prepare('INSERT INTO observations VALUES(?,?,?,?)').run(profileId,enrolled.revision,enrolled.trust_digest,new Date().toISOString());}if(fault==='before_commit')process.exit(96);this.db.exec('COMMIT');if(fault==='after_commit')process.exit(95);return {...enrolled,profile,idempotent};}catch(e){this.db.exec('ROLLBACK');throw e;}}
 status(profileId){const row=this.db.prepare('SELECT * FROM profiles WHERE id=?').get(profileId);if(!row)throw Error('REVIEWER_PROFILE_NOT_ENROLLED');return {profile:JSON.parse(row.anchors),revision:row.revision,trust_digest:row.digest};}
 recover({profileId,trust,request}){const incoming=resolve(request.directory);if(this.path===incoming||this.path.startsWith(incoming+sep))throw Error('REVIEWER_STATE_INSIDE_BACKUP');const enrolled=this.observe({profileId,trust});if(request.tenant!==enrolled.profile.tenant||request.purpose!==enrolled.profile.purpose)throw Error('REVIEWER_REQUEST_SCOPE');const result=recoverBackup({...request,keys:enrolled.keys});return {...result,reviewer_profile:profileId,retained_revision:enrolled.revision,online_freshness:'unknown',floor_committed_before_recovery:true};}
 close(){this.db.close();}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const c=JSON.parse(readFileSync(process.argv[2])),s=new ReviewerState(c.path);try{if(!['enroll','observe','recover','status'].includes(c.operation))throw Error('REVIEWER_OPERATION');console.log(JSON.stringify(s[c.operation](c.request)));}finally{s.close();}}catch(e){console.error(e.message);process.exitCode=2;}}
