import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {createServer} from 'node:http';
import {randomBytes,timingSafeEqual,createCipheriv,createDecipheriv} from 'node:crypto';
import {mkdirSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {canonical,digest,signed} from '../../robot-black-box-contract/src/index.mjs';
import {localKey,atomicWrite} from '../../robot-black-box-recorder/src/index.mjs';
import {verifyBundle} from '../../robot-black-box-verifier/src/index.mjs';
import {evaluateGovernance,PROFILE} from '../../robot-black-box-governance/src/index.mjs';
import {DurableReportStore,reportBytes} from '../../robot-black-box-grc-bridge/src/durable.mjs';
import {evaluate,DEFAULT_POLICY} from '../../robot-black-box-policy/src/index.mjs';
import {consolidatedReview,citedExcerpt} from '../../../scripts/robot-black-box/consolidated-review.mjs';
export class LocalCommercial {
 constructor(directory,execution) {
  this.directory=resolve(directory);mkdirSync(this.directory,{recursive:true,mode:0o700});this.key=localKey(join(this.directory,'audit-custody'),'service-audit-local');this.execution=execution;
  this.trust=JSON.parse(readFileSync(join(execution,'custody','trust.json'),'utf8'));this.heads=JSON.parse(readFileSync(join(execution,'custody','witness','latest-heads.json'),'utf8'));
  this.db=new DatabaseSync(join(this.directory,'fleet.sqlite'));this.db.exec('PRAGMA journal_mode=WAL;PRAGMA synchronous=FULL;CREATE TABLE IF NOT EXISTS runs(tenant TEXT,id TEXT,bundle_path TEXT,report TEXT,PRIMARY KEY(tenant,id));CREATE TABLE IF NOT EXISTS policies(tenant TEXT,id TEXT,body TEXT,state TEXT,author TEXT,reviewer TEXT,PRIMARY KEY(tenant,id));CREATE TABLE IF NOT EXISTS investigations(tenant TEXT,id INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT,note TEXT,citations TEXT,actor TEXT);CREATE TABLE IF NOT EXISTS retention(tenant TEXT,run_id TEXT,state TEXT,PRIMARY KEY(tenant,run_id));CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,bytes TEXT);');
  const credentialPath=join(this.directory,'demo-credentials.json');
  if(!existsSync(credentialPath)){const identities=[];for(const tenant of ['tenant-a','tenant-b'])for(const role of ['author','reviewer','investigator','admin'])identities.push({tenant,role,subject:`${tenant}-${role}`,token:randomBytes(32).toString('hex')});atomicWrite(credentialPath,JSON.stringify(identities,null,2));}
  this.identities=JSON.parse(readFileSync(credentialPath,'utf8'));this.durable=new DurableReportStore(join(this.directory,'durable-grc.sqlite'),this.key);
 }
 identity(token){const bytes=Buffer.from(token??'');return this.identities.find(x=>{const other=Buffer.from(x.token);return bytes.length===other.length&&timingSafeEqual(bytes,other);});}
 audit(actor,action,target,outcome) {const prior=this.db.prepare('SELECT bytes FROM audit ORDER BY id DESC LIMIT 1').get();const priorDigest=prior?JSON.parse(prior.bytes).authentication.event_digest:'0'.repeat(64);const entry=signed({schema:'rbb.service.audit.v1',tenant:actor?.tenant??'anonymous',subject:actor?.subject??'anonymous',action,target,outcome,at:new Date().toISOString(),previous_digest:priorDigest},this.key.keyId,this.key.privateKey,'AUDIT');this.db.prepare('INSERT INTO audit(bytes) VALUES(?)').run(canonical(entry));return entry;}
 require(actor,roles){if(!actor||!roles.includes(actor.role))throw Object.assign(Error('Forbidden role'),{status:403});}
 ingest(actor,case_id){this.require(actor,['admin']);if(!/^(?:H[0-6]|G(?:[0-9]|1[0-9]|2[0-5]))$/.test(case_id))throw Object.assign(Error('Unknown public demo case'),{status:400});const path=join(this.execution,'cases',case_id);const report=verifyBundle(path,this.trust,{latestHeads:this.heads});if(report.tenant_ref!==actor.tenant)throw Object.assign(Error('Tenant mismatch'),{status:403});const e=evaluate(report,DEFAULT_POLICY,this.trust);const {facts,...summary}=report;this.db.prepare('INSERT INTO runs VALUES(?,?,?,?) ON CONFLICT(tenant,id) DO UPDATE SET report=excluded.report').run(actor.tenant,report.run_id,path,canonical({verification:summary,evaluation:e,...(case_id.startsWith('G')?{governance:evaluateGovernance(report,this.trust)??{status:'unknown',results:[{status:'unknown',code:'GOVERNANCE_EVIDENCE_UNUSABLE'}]}}:{})}));this.captureManagedArtifacts(actor,report.run_id,path);this.audit(actor,'ingest',report.run_id,'accepted_verified_or_quarantined');return {run_id:report.run_id,...e};}
 captureManagedArtifacts(actor,id,bundle) {
  const folder=join(this.directory,'managed',actor.tenant,id);if(existsSync(join(folder,'metadata.json')))return;
  const report=verifyBundle(bundle,this.trust,{latestHeads:this.heads});if(report.integrity!=='valid')return;
  const objects={};for(const e of report.facts)for(const ref of e.artifact_refs)objects[ref.object_id]=readFileSync(join(bundle,'objects',ref.object_id)).toString('base64');
  const key=randomBytes(32),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);const ciphertext=Buffer.concat([cipher.update(canonical(objects)),cipher.final()]);
  atomicWrite(join(folder,'key'),key);atomicWrite(join(folder,'ciphertext'),ciphertext);atomicWrite(join(folder,'metadata.json'),canonical({schema:'rbb.managed.copy.v1',iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),source:'public synthetic original replay remains outside managed copy',object_ids:Object.keys(objects)}));
 }
 managedArtifacts(actor,id) {
  const folder=join(this.directory,'managed',actor.tenant,id);if(!existsSync(join(folder,'metadata.json')))return {availability:'not_captured',objects:{}};
  if(!existsSync(join(folder,'key')))return {availability:'deleted_managed_copy',objects:{}};
  const meta=JSON.parse(readFileSync(join(folder,'metadata.json'),'utf8'));const decipher=createDecipheriv('aes-256-gcm',readFileSync(join(folder,'key')),Buffer.from(meta.iv,'base64'));decipher.setAuthTag(Buffer.from(meta.tag,'base64'));
  return {availability:'available',objects:JSON.parse(Buffer.concat([decipher.update(readFileSync(join(folder,'ciphertext'))),decipher.final()]).toString())};
 }
 hold(actor,id,enabled) {this.require(actor,['admin']);this.run(actor,id);this.db.prepare('INSERT INTO retention VALUES(?,?,?) ON CONFLICT(tenant,run_id) DO UPDATE SET state=excluded.state').run(actor.tenant,id,enabled?'held':'active');this.audit(actor,'retention.hold',id,enabled?'held':'released');return {state:enabled?'held':'active'};}
 deleteManaged(actor,id) {
  this.require(actor,['admin']);this.run(actor,id);const state=this.db.prepare('SELECT state FROM retention WHERE tenant=? AND run_id=?').get(actor.tenant,id);if(state?.state==='held')throw Object.assign(Error('Managed copy is held'),{status:409});
  const folder=join(this.directory,'managed',actor.tenant,id);rmSync(join(folder,'key'),{force:true});rmSync(join(folder,'ciphertext'),{force:true});
  const tombstone=signed({schema:'rbb.deletion.local.v1',tenant:actor.tenant,run_id:id,actor:actor.subject,at:new Date().toISOString(),scope:'managed synthetic copy and its local key only; original public replay, signed envelopes and audit retained'},this.key.keyId,this.key.privateKey,'DELETION');atomicWrite(join(folder,'deletion.json'),canonical(tombstone));this.db.prepare('INSERT INTO retention VALUES(?,?,?) ON CONFLICT(tenant,run_id) DO UPDATE SET state=excluded.state').run(actor.tenant,id,'managed_copy_deleted');this.audit(actor,'retention.delete',id,'managed_copy_deleted');return {state:'managed_copy_deleted',tombstone,limitations:'No guarantee of filesystem secure erasure, backups, external copies or original public replay deletion. No private data captured.'};
 }
 snapshot(actor,path) {
  this.require(actor,['admin']);if(existsSync(path))throw Error('Snapshot exists');const copy=new DatabaseSync(path);
  try {copy.exec('CREATE TABLE runs(tenant TEXT,id TEXT,bundle_path TEXT,report TEXT);CREATE TABLE policies(tenant TEXT,id TEXT,body TEXT,state TEXT,author TEXT,reviewer TEXT);CREATE TABLE retention(tenant TEXT,run_id TEXT,state TEXT);CREATE TABLE investigations(tenant TEXT,id INTEGER,run_id TEXT,note TEXT,citations TEXT,actor TEXT);');
   for(const table of ['runs','policies','retention','investigations'])for(const row of this.db.prepare('SELECT * FROM '+table+' WHERE tenant=?').all(actor.tenant))copy.prepare('INSERT INTO '+table+' VALUES('+Object.keys(row).map(()=>'?').join(',')+')').run(...Object.values(row));
  }finally{copy.close();}
  const manifest=signed({schema:'rbb.snapshot.local.v1',tenant:actor.tenant,sha256:digest(readFileSync(path)),at:new Date().toISOString(),scope:'tenant metadata only; source bundles, audit custody and recovery keys outside snapshot'},this.key.keyId,this.key.privateKey,'SNAPSHOT');atomicWrite(path+'.manifest.json',canonical(manifest));this.audit(actor,'backup.snapshot','fleet.sqlite','tenant_local_metadata_snapshot');return {path,tenant:actor.tenant,manifest,scope:manifest.scope};
 }

 runs(actor){return this.db.prepare('SELECT id,report FROM runs WHERE tenant=?').all(actor.tenant).map(x=>({id:x.id,...JSON.parse(x.report)}));}
 run(actor,id){const row=this.db.prepare('SELECT * FROM runs WHERE tenant=? AND id=?').get(actor.tenant,id);if(!row)throw Object.assign(Error('Run not found'),{status:404});return row;}
 monitor(actor){const rows=this.runs(actor);return {tenant:actor.tenant,scope:'local synthetic fleet',runs:rows.length,exceptions:rows.filter(x=>x.evaluation.authorization!=='pass'||x.verification.integrity!=='valid'||x.verification.completeness!=='complete'||(x.governance&&x.governance.status!=='pass')).map(x=>({run_id:x.id,authorization:x.evaluation.authorization,integrity:x.verification.integrity,governance:x.governance?.status??'not_applicable',reasons:[...x.evaluation.results,...(x.governance?.results??[])].filter(r=>r.status!=='pass').map(r=>r.code)})),custody:'same-machine demo; no enterprise key custody, OIDC, retention SLA or hosted ingestion'};}
 export(actor,id,purpose){this.require(actor,['admin','investigator','reviewer']);const row=this.run(actor,id);const governanceRun=id.startsWith('demo-G');if(purpose!==(governanceRun?PROFILE.purpose:'handover_evaluation')){this.audit(actor,'export',id,'denied_purpose');throw Object.assign(Error('Purpose denied'),{status:403});}const report=verifyBundle(row.bundle_path,this.trust,{latestHeads:this.heads});this.audit(actor,'export',id,'allowed');const governance=governanceRun?evaluateGovernance(report,this.trust)??{status:'unknown',results:[{status:'unknown',code:'GOVERNANCE_EVIDENCE_UNUSABLE'}]}:null,evaluation=evaluate(report,DEFAULT_POLICY,this.trust),content=reportBytes(report,evaluation,governance);const durable_report=this.durable.attach({...actor,purpose},{id,purpose,content,expected_digest:digest(content)});return {manifest:JSON.parse(readFileSync(join(row.bundle_path,'manifest.json'),'utf8')),events:readFileSync(join(row.bundle_path,'events.ndjson'),'utf8'),checkpoints:JSON.parse(readFileSync(join(row.bundle_path,'checkpoints.json'),'utf8')),verification:report,...(governance?{governance}:{}),durable_report,managed_artifacts:this.managedArtifacts(actor,id),export_scope:'signed non-private synthetic records and durable local report; no private custody keys'};}
 policy(actor,id,body){this.require(actor,['author','admin']);if(!/^[a-z0-9-]{1,64}$/.test(id))throw Object.assign(Error('Bad policy id'),{status:400});if(canonical(body)!==canonical(DEFAULT_POLICY))throw Object.assign(Error('Only verified local policy profile supported'),{status:400});this.db.prepare('INSERT INTO policies VALUES(?,?,?,?,?,NULL)').run(actor.tenant,id,canonical(body),'draft',actor.subject);this.audit(actor,'policy.draft',id,'draft');return {id,state:'draft',digest:digest(canonical(body))};}
 approve(actor,id){this.require(actor,['reviewer']);const p=this.db.prepare('SELECT * FROM policies WHERE tenant=? AND id=?').get(actor.tenant,id);if(!p)throw Object.assign(Error('Policy not found'),{status:404});if(p.author===actor.subject||p.state!=='draft')throw Object.assign(Error('Approval requires independent reviewer and draft'),{status:409});this.db.prepare('UPDATE policies SET state=?,reviewer=? WHERE tenant=? AND id=?').run('approved',actor.subject,actor.tenant,id);this.audit(actor,'policy.approve',id,'approved');return {id,state:'approved',activation:'advisory registry only; replay evaluations retain pinned original policy'};}
 investigate(actor,id,note,citations){this.require(actor,['investigator']);const row=this.run(actor,id);const report=verifyBundle(row.bundle_path,this.trust,{latestHeads:this.heads});if(typeof note!=='string'||note.length>2000||!Array.isArray(citations)||!citations.length||citations.some(x=>!report.facts.some(e=>e.event_id===x)))throw Object.assign(Error('Citations must reference accessible verified events'),{status:400});this.db.prepare('INSERT INTO investigations(tenant,run_id,note,citations,actor) VALUES(?,?,?,?,?)').run(actor.tenant,id,note,canonical(citations),actor.subject);this.audit(actor,'investigation.note',id,'stored_human_note');return {stored:true,claim_class:'human_comment_not_verified_causation'};}
 retention(actor,id){this.require(actor,['admin']);this.run(actor,id);const current=this.db.prepare('SELECT state FROM retention WHERE tenant=? AND run_id=?').get(actor.tenant,id);if(current?.state==='held')return {state:'held',deletion_requested:true};this.db.prepare('INSERT INTO retention VALUES(?,?,?) ON CONFLICT(tenant,run_id) DO UPDATE SET state=excluded.state').run(actor.tenant,id,'deletion_requested');this.audit(actor,'retention.request',id,'queued_not_deleted');return {state:'deletion_requested',limitations:'This public synthetic replay demo records requests only. Use local hold/deletion endpoints for managed synthetic-copy demonstration. No private capture, production backup deletion or retention guarantees.'};}
 close(){this.durable.close();this.db.close();}
}
export function server(service,{port=4318}={}) {
 return createServer(async(req,res)=>{
  const send=(status,body,type='application/json')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'"});res.end(type==='application/json'?JSON.stringify(body):body);};
  try {
   const u=new URL(req.url,'http://127.0.0.1');
   if(req.method==='GET'&&u.pathname==='/'){send(200,readFileSync(new URL('./console.html',import.meta.url),'utf8'),'text/html');return;}
   if(req.method==='GET'&&u.pathname==='/console.js'){send(200,readFileSync(new URL('./console.js',import.meta.url),'utf8'),'text/javascript');return;}
   const actor=service.identity(req.headers.authorization?.replace(/^Bearer /,''));if(!actor){send(401,{error:'Local demo bearer credential required'});return;}
   if(req.headers.origin&&req.headers.origin!==`http://127.0.0.1:${port}`&&req.headers.origin!==`http://localhost:${port}`){send(403,{error:'Origin denied'});return;}
   let body={};if(req.method==='POST'){let bytes=0;const chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>65536)throw Object.assign(Error('Body too large'),{status:413});chunks.push(chunk);}body=JSON.parse(Buffer.concat(chunks).toString()||'{}');}
   const parts=u.pathname.split('/').filter(Boolean);
   if(req.method==='GET'&&(u.pathname==='/v1/review'||u.pathname==='/v1/review/evidence')){service.require(actor,['admin','investigator','reviewer']);if(actor.tenant!=='tenant-a')return send(404,{error:'Public review unavailable for this tenant'});if(u.searchParams.get('purpose')!=='investigation_review')return send(403,{error:'Purpose denied'});if([...u.searchParams.keys()].some(k=>!['purpose',...(u.pathname.endsWith('/evidence')?['source']:[])].includes(k)))return send(400,{error:'Unknown review parameter'});return send(200,u.pathname.endsWith('/evidence')?citedExcerpt(u.searchParams.get('source')??''):consolidatedReview());}
   if(req.method==='GET'&&u.pathname==='/v1/runs')return send(200,service.runs(actor));
   if(req.method==='GET'&&u.pathname==='/v1/monitor')return send(200,service.monitor(actor));
   if(req.method==='POST'&&u.pathname==='/v1/ingest')return send(201,service.ingest(actor,body.case_id));
   if(req.method==='POST'&&u.pathname==='/v1/policies')return send(201,service.policy(actor,body.id,body.policy));
   if(req.method==='POST'&&parts[1]==='policies'&&parts[3]==='approve')return send(200,service.approve(actor,parts[2]));
   if(req.method==='GET'&&parts[1]==='runs'&&parts[3]==='bundle')return send(200,service.export(actor,parts[2],u.searchParams.get('purpose')));
   if(req.method==='GET'&&parts[1]==='runs'&&parts[3]==='durable-report'){service.run(actor,parts[2]);const purpose=u.searchParams.get('purpose');return send(200,service.durable.read({...actor,purpose},parts[2],purpose));}
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='durable-hold'){service.run(actor,parts[2]);service.durable.hold({...actor,purpose:body.purpose},parts[2],body.purpose,body.enabled);return send(200,{held:body.enabled});}
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='delete-durable'){service.run(actor,parts[2]);return send(200,service.durable.remove({...actor,purpose:body.purpose},parts[2],body.purpose));}
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='notes')return send(201,service.investigate(actor,parts[2],body.note,body.citations));
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='hold')return send(200,service.hold(actor,parts[2],body.enabled===true));
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='delete-managed')return send(200,service.deleteManaged(actor,parts[2]));
   if(req.method==='POST'&&parts[1]==='runs'&&parts[3]==='deletion-requests')return send(202,service.retention(actor,parts[2]));
   send(404,{error:'Not found'});
  }catch(err){send(err.status??400,{error:err.message});}
 });
}
if(process.argv[1]&&resolve(process.argv[1])===resolve(fileURLToPath(import.meta.url))){const dir=process.argv[2]??'.rbb/commercial';const execution=process.argv[3]??'.rbb/local-demo';const service=new LocalCommercial(dir,execution);const admin=service.identities.find(x=>x.tenant==='tenant-a'&&x.role==='admin');for(let i=0;i<7;i++)service.ingest(admin,`H${i}`);for(let i=0;i<26;i++)if(existsSync(join(execution,'cases','G'+i,'manifest.json')))service.ingest(admin,'G'+i);const port=Number(process.env.RBB_PORT??4318);const s=server(service,{port});s.listen(port,'127.0.0.1',()=>console.log(`Robot Black Box local demo: http://127.0.0.1:${port}; credentials stored privately at ${resolve(dir)}/demo-credentials.json`));for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>s.close(()=>{service.close();process.exit(0);}));}
