import {canonical,digest,authenticate,exact} from '../../robot-black-box-contract/src/index.mjs';
export function captureQuality(verification,trust,profile,{at=new Date().toISOString()}={}) {
 const results=[],channels=[];const add=(status,code,event_ids=[],pointer='$')=>results.push({status,code,event_ids,pointer});
 const report={schema:'rbb.capture.quality.v1',run_id:verification.run_id,bundle_digest:verification.bundle_digest,profile_digest:profile?digest(canonical(profile)):null,evaluated_at:at,status:'unknown',channels,results,online_source_freshness:'unknown',calibration_assurance:'unknown',scope:'declared synthetic channel/time quality; separate from integrity and action authorization',limitations:['No calibrated hardware measurement, source truth, complete physical capture, crash survival or aviation qualification.','Receive/verify time and synthetic observation time are distinct; no live-source freshness inference.']};
 if(verification.integrity!=='valid'||!verification.facts?.length){add('unknown','CAPTURE_SIGNED_FACTS_UNUSABLE');return report;}
 let body;
 try {
  body=authenticate(profile,trust.authorities,'CAPTURE-PROFILE');const v2=body.schema==='rbb.capture.profile.v2';exact(body,['schema','issuer','tenant','system_id','run_id','mode','not_before','expires_at','channels',...(v2?['clock_domains','max_receipt_interval_ms']:[])],'CAPTURE_PROFILE');if(v2){exact(body.clock_domains,['source','observation_epoch','receipt'],'CAPTURE_CLOCK_DOMAINS');if(body.clock_domains.source!=='simulation_elapsed'||body.clock_domains.observation_epoch!=='2000-01-01T00:00:00.000Z'||body.clock_domains.receipt!=='uncalibrated_local_host'||!Number.isFinite(body.max_receipt_interval_ms)||body.max_receipt_interval_ms<=0)throw Error('CAPTURE_CLOCK_DOMAINS');report.clock_domains=body.clock_domains;}
  if(!['rbb.capture.profile.v1','rbb.capture.profile.v2'].includes(body.schema)||body.issuer!==profile.authentication.key_id||body.tenant!==verification.tenant_ref||body.run_id!==verification.run_id||body.mode!=='synthetic_replay'||body.system_id!==verification.facts[0].system_id||!trust.authorities[body.issuer].tenants?.includes(body.tenant))throw Error('CAPTURE_PROFILE_SCOPE');
  if(!Number.isFinite(Date.parse(at))||!Number.isFinite(Date.parse(body.not_before))||!Number.isFinite(Date.parse(body.expires_at))||Date.parse(at)<Date.parse(body.not_before)||Date.parse(at)>=Date.parse(body.expires_at))throw Error('CAPTURE_PROFILE_EXPIRED');
  if(!Array.isArray(body.channels)||!body.channels.length||body.channels.length>32)throw Error('CAPTURE_CHANNEL_BOUND');
  const seen=new Set();for(const c of body.channels){exact(c,['id','sensor_id','units','coordinate_frame','clock_id','max_uncertainty_ms','expected_count','max_interval_ms','calibration'],'CAPTURE_CHANNEL');if(typeof c.id!=='string'||! /^[a-z0-9_-]{1,64}$/.test(c.id)||seen.has(c.id)||seen.has('sensor:'+c.sensor_id)||typeof c.sensor_id!=='string'||!c.sensor_id||['units','coordinate_frame','clock_id'].some(k=>typeof c[k]!=='string'||!c[k])||!Number.isFinite(c.max_uncertainty_ms)||c.max_uncertainty_ms<0||!Number.isSafeInteger(c.expected_count)||c.expected_count<1||c.expected_count>100000||(c.max_interval_ms!==null&&(!Number.isFinite(c.max_interval_ms)||c.max_interval_ms<=0))||c.calibration!=='unverified_synthetic_declaration')throw Error('CAPTURE_CHANNEL_SCHEMA');seen.add(c.id);seen.add('sensor:'+c.sensor_id);}
 }catch(e){add('unknown',e.message);return report;}
 const facts=verification.facts,closed=facts.at(-1).event_type==='run.closed';let previous=null;
 for(const e of facts){const time=Date.parse(e.observed_at);if(!Number.isFinite(time)){add('unknown','OBSERVATION_TIME_UNAVAILABLE',[e.event_id],'$.observed_at');continue;}if(previous&&e.clock.clock_id===previous.clock.clock_id&&time<Date.parse(previous.observed_at))add('fail','OBSERVATION_TIME_ROLLBACK',[previous.event_id,e.event_id],'$.observed_at');previous=e;}
 const observations=facts.filter(e=>e.event_type==='observation.recorded');
 for(const c of body.channels){const events=observations.filter(e=>e.payload.sensor_id===c.sensor_id),ids=events.map(e=>e.event_id),summary={id:c.id,sensor_id:c.sensor_id,recorded_count:events.length,declared_expected_count:c.expected_count,max_observed_interval_ms:null,sampling_assurance:'unknown',calibration_assurance:'unknown'};channels.push(summary);
  if(!events.length)add(closed?'fail':'unknown',closed?'REQUIRED_CHANNEL_MISSING':'REQUIRED_CHANNEL_NOT_YET_OBSERVED',[],`$.channels.${c.id}`);else if(events.length!==c.expected_count)add(closed?'fail':'unknown',closed?'CHANNEL_COUNT_MISMATCH':'CHANNEL_COUNT_NOT_YET_ESTABLISHED',ids,`$.channels.${c.id}.expected_count`);
  for(const e of events){if(e.payload.units!==c.units||e.payload.coordinate_frame!==c.coordinate_frame)add('fail','CHANNEL_SEMANTICS_MISMATCH',[e.event_id],`$.channels.${c.id}`);if(e.clock.clock_id!==c.clock_id||e.clock.status!=='synchronized'||e.clock.max_uncertainty_ms>c.max_uncertainty_ms)add('unknown','CHANNEL_CLOCK_UNCERTAIN',[e.event_id],`$.channels.${c.id}.clock_id`);}
  if(c.max_interval_ms===null)add('unknown','CHANNEL_SAMPLING_NOT_SPECIFIED',ids,`$.channels.${c.id}.max_interval_ms`);
  else if(events.length<2)add('unknown','CHANNEL_SAMPLING_INSUFFICIENT',ids,`$.channels.${c.id}.max_interval_ms`);
  else {if(body.schema==='rbb.capture.profile.v2')for(let i=1;i<events.length;i++)if(BigInt(events[i].monotonic_ns)<=BigInt(events[i-1].monotonic_ns))add('fail','CHANNEL_OFFSET_NOT_INCREASING',[events[i-1].event_id,events[i].event_id],`$.channels.${c.id}`);const intervals=events.slice(1).map((e,i)=>e.clock.clock_id===events[i].clock.clock_id&&e.clock.status==='synchronized'&&events[i].clock.status==='synchronized'?(BigInt(e.monotonic_ns)-BigInt(events[i].monotonic_ns)<=BigInt(Number.MAX_SAFE_INTEGER)?Number(BigInt(e.monotonic_ns)-BigInt(events[i].monotonic_ns))/1000000:null):null);if(intervals.some(x=>x===null))add('unknown','CHANNEL_SAMPLING_CLOCK_INCOMPARABLE',ids,`$.channels.${c.id}.clock_id`);else{summary.max_observed_interval_ms=Math.max(...intervals);summary.sampling_assurance=summary.max_observed_interval_ms>c.max_interval_ms?'fail':'declared_interval_satisfied';if(summary.sampling_assurance==='fail')add('fail','CHANNEL_INTERVAL_EXCEEDED',ids,`$.channels.${c.id}.max_interval_ms`);}}
  add('unknown','CHANNEL_CALIBRATION_UNVERIFIED',ids,`$.channels.${c.id}.calibration`);
 }
 if(body.schema==='rbb.capture.profile.v2')for(let i=1;i<observations.length;i++){const delta=Date.parse(observations[i].received_at)-Date.parse(observations[i-1].received_at);if(delta>body.max_receipt_interval_ms)add('fail','LOCAL_RECEIPT_INTERVAL_EXCEEDED',[observations[i-1].event_id,observations[i].event_id],'$.received_at');if(delta<0)add('unknown','LOCAL_RECEIPT_CLOCK_ROLLBACK',[observations[i-1].event_id,observations[i].event_id],'$.received_at');}
 for(const e of observations)if(!body.channels.some(c=>c.sensor_id===e.payload.sensor_id))add('unknown','UNPROFILED_CHANNEL',[e.event_id],'$.payload.sensor_id');
 for(const e of facts.filter(e=>e.event_type==='telemetry.gap'))add('fail','DECLARED_CAPTURE_GAP',[e.event_id],'$.payload.missing_interval');
 if(verification.completeness!=='complete')add('unknown','CAPTURE_RUN_INCOMPLETE');
 add('unknown','LIVE_CAPTURE_NOT_OBSERVED');report.status=results.some(r=>r.status==='fail')?'fail':'unknown';return report;
}
