import {readFileSync,readdirSync,lstatSync,openSync,closeSync,fstatSync,constants,realpathSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {canonical,digest,authenticate} from '../../packages/robot-black-box-contract/src/index.mjs';
import {verifyBundle} from '../../packages/robot-black-box-verifier/src/index.mjs';
import {captureQuality} from '../../packages/robot-black-box-verifier/src/capture-quality.mjs';
import {evaluate,DEFAULT_POLICY} from '../../packages/robot-black-box-policy/src/index.mjs';
export function inventory(root){
 const files=[];let total=0,entries=0;const walk=(dir,prefix='')=>{for(const name of readdirSync(dir).sort()){if(++entries>1024||prefix.split('/').length>16)throw Error('INTAKE_LIMIT');if(!/^[A-Za-z0-9_.-]+$/.test(name)||name==='.'||name==='..')throw Error('UNSAFE_PATH');const path=join(dir,name),relative=prefix+name,s=lstatSync(path);if(s.isSymbolicLink())throw Error('SYMLINK_REJECTED');if(s.isDirectory())walk(path,relative+'/');else{if(!s.isFile()||s.nlink!==1)throw Error('SPECIAL_OR_HARDLINK_REJECTED');if(s.size>16*1024*1024||(total+=s.size)>32*1024*1024||files.length>=512)throw Error('INTAKE_LIMIT');const fd=openSync(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const current=fstatSync(fd);if(current.ino!==s.ino||current.dev!==s.dev||current.size!==s.size||current.nlink!==1)throw Error('FILE_CHANGED');const bytes=readFileSync(fd);if(bytes.length!==s.size)throw Error('FILE_CHANGED');if(relative!=='package-manifest.json')files.push({path:relative,bytes:bytes.length,sha256:digest(bytes)});}finally{closeSync(fd);}}}};
 if(lstatSync(root).isSymbolicLink())throw Error('SYMLINK_ROOT_REJECTED');walk(realpathSync(root));return files;
}
export function review(root,{currentTrust=null}={}){
 const result={schema:'rbb.portable.review.v1',package_completeness:'unknown',cryptographic_integrity:'unknown',current_trust:currentTrust?'reviewer_supplied_snapshot_not_online_attested':'unknown_not_supplied',verifier_authenticity:'requires_external_pin_or_trusted_tool_copy',source_truth:'unknown',external_custody:'unknown',hardware_qualification:'unknown',cases:[],errors:[]};
 try{const actual=inventory(root),manifest=JSON.parse(readFileSync(join(root,'package-manifest.json')));if(manifest.schema!=='rbb.portable.package.v1'||!Array.isArray(manifest.files)||manifest.files.some(f=>!/^([A-Za-z0-9_-]+\/)*[A-Za-z0-9_.-]+$/.test(f.path)||f.path.split('/').includes('..'))||canonical(actual)!==canonical(manifest.files))throw Error('PACKAGE_INVENTORY_MISMATCH');result.package_completeness='complete';result.transport_manifest_sha256=digest(readFileSync(join(root,'package-manifest.json')));const trust=JSON.parse(readFileSync(join(root,'evidence/trust.json'))),heads=JSON.parse(readFileSync(join(root,'evidence/latest-heads.json'))),execution=JSON.parse(readFileSync(join(root,'evidence/execution.json')));
 for(const c of execution.cases){if(!/^[A-Za-z0-9_-]+$/.test(c.name))throw Error('UNSAFE_CASE');const path=join(root,'evidence/cases',c.name),receipt=JSON.parse(readFileSync(join(path,'capture-quality.json')));authenticate(receipt,trust.producers,'CAPTURE-QUALITY');if(digest(canonical(receipt))!==c.receipt_digest)throw Error('RECEIPT_DIGEST_MISMATCH');const verification=verifyBundle(path,trust,{latestHeads:heads}),quality=captureQuality(verification,trust,receipt.profile,{at:receipt.at});if(canonical(quality)!==canonical(receipt.quality))throw Error('DIAGNOSTIC_RECOMPUTATION_MISMATCH');const entry={name:c.name,as_of:receipt.at,historical_snapshot_integrity:verification.integrity,evidence_completeness:verification.completeness,anchoring:verification.anchoring,authorization:evaluate(verification,DEFAULT_POLICY,trust),capture_quality:quality,receipt_authenticated:true};if(currentTrust){const v=verifyBundle(path,currentTrust,{latestHeads:null});entry.reviewer_snapshot_integrity=v.integrity;entry.capture_quality_at_review=captureQuality(v,currentTrust,receipt.profile);}result.cases.push(entry);}
 result.cryptographic_integrity=result.cases.every(c=>c.historical_snapshot_integrity==='valid')?'valid':'unknown';result.historical_trust='included_publisher_snapshot_as_of_receipts_not_independent_enrollment';
 }catch(e){result.errors.push(e.message);result.package_completeness='incomplete_or_rejected';result.cryptographic_integrity='unknown';result.cases=[];}
 return result;
}
if(process.argv[1]&&realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){const root=resolve(process.argv[2]??'.');const currentTrust=process.argv[3]?JSON.parse(readFileSync(process.argv[3])):null;const report=review(root,{currentTrust});console.log(JSON.stringify(report));process.exitCode=report.errors.length?2:0;}
