const form=document.querySelector('#login');
const text=(selector,value)=>{document.querySelector(selector).textContent=String(value);};
form.addEventListener('submit',async(event)=>{
 event.preventDefault();document.querySelector('#assurance').hidden=true;document.querySelector('#review-public').disabled=true;document.querySelector('#review-cards').replaceChildren();document.querySelector('#review-citation-body').textContent='';document.querySelector('#evidence').hidden=true;text('#evidence-body','');document.querySelector('#rows').replaceChildren();text('#runs','—');text('#exceptions','—');const token=document.querySelector('#token').value;
 const request=async(path)=>{const response=await fetch(path,{headers:{Authorization:'Bearer '+token}});const body=await response.json();if(!response.ok)throw Error(body.error);return body;};
 try {
  const [runs,monitor]=await Promise.all([request('/v1/runs'),request('/v1/monitor')]);document.querySelector('#review-public').disabled=false;text('#runs',runs.length);text('#exceptions',monitor.exceptions.length);text('#status',monitor.tenant+' · '+monitor.custody);document.querySelector('#status').className='';
  const rows=document.querySelector('#rows');rows.replaceChildren();
  for(const run of runs){const tr=document.createElement('tr');const values=[run.id,run.verification.integrity,run.evaluation.authorization,run.evaluation.task_outcome,run.governance?.status??'—',[...run.evaluation.results,...(run.governance?.results??[])].filter(x=>x.status!=='pass').map(x=>x.code).join(', ')||(run.governance?'GOVERNANCE_CONTROLS_SATISFIED':'APPROVAL_VALID_FOR_EXECUTION')];for(const [i,value]of values.entries()){const td=document.createElement('td');const span=document.createElement('span');span.textContent=value;if(i===0){const button=document.createElement('button');button.className='run-link';button.textContent=value;button.addEventListener('click',async()=>{try{const exported=await request('/v1/runs/'+encodeURIComponent(run.id)+'/bundle?purpose='+(run.governance?'governance_evaluation':'handover_evaluation'));const g=exported.governance;const evidence={run_id:run.id,bundle_digest:exported.verification.bundle_digest,integrity:exported.verification.integrity,anchoring:exported.verification.anchoring,governance:g??'not applicable',durable_report:exported.durable_report,artifact_refs:exported.verification.facts.flatMap(e=>e.artifact_refs)};document.querySelector('#evidence').hidden=false;text('#evidence-body',JSON.stringify(evidence,null,2));document.querySelector('#evidence').scrollIntoView({block:'start'});}catch(error){text('#status',error.message);document.querySelector('#status').className='error';}});td.append(button);tr.append(td);continue;}if(i===1||i===2||i===4)span.className='badge '+value;td.append(span);tr.append(td);}rows.append(tr);}
  if(!runs.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='No runs in this tenant. Tenant boundaries are enforced.';tr.append(td);rows.append(tr);}
 }catch(error){text('#status',error.message);document.querySelector('#status').className='error';}
});

const clearReview=()=>{document.querySelector('#assurance').hidden=true;document.querySelector('#review-public').disabled=true;document.querySelector('#review-citation').hidden=true;document.querySelector('#review-citation-body').textContent='';for(const id of ['review-cards','review-cases','aircraft-gaps','review-provenance'])document.querySelector('#'+id).replaceChildren();for(const id of ['review-time','review-sources','aircraft-scope'])text('#'+id,'');document.querySelector('#rows').replaceChildren();document.querySelector('#evidence').hidden=true;text('#evidence-body','');text('#runs','—');text('#exceptions','—');};
document.querySelector('#token').addEventListener('input',clearReview);
document.querySelector('#review-public').addEventListener('click',async()=>{
 const button=document.querySelector('#review-public');button.disabled=true;document.querySelector('#assurance').hidden=true;document.querySelector('#review-citation').hidden=true;
 const token=document.querySelector('#token').value;const request=async path=>{const r=await fetch(path,{headers:{Authorization:'Bearer '+token}});const b=await r.json();if(!r.ok)throw Error(b.error);return b;};
 const el=(tag,value,className='')=>{const node=document.createElement(tag);if(value!==undefined)node.textContent=value;node.className=className;return node;};
 try{const report=await request('/v1/review?purpose=investigation_review');if(token!==document.querySelector('#token').value)return;text('#review-time','Generated '+report.generated_at+' · '+report.tenant+' · '+report.purpose);const tags=document.querySelector('#review-provenance');tags.replaceChildren();for(const p of report.provenance){const tag=el('span',p.tag.replaceAll('_',' '),'badge');tag.title=p.note;tags.append(tag);}const cards=document.querySelector('#review-cards');cards.replaceChildren();
 for(const s of report.sections){const card=el('article',undefined,'review-card');card.append(el('h3',s.title));for(const [label,value] of [['Historical evidence',s.historical],['Present check',s.present]]){card.append(el('h4',label),el('span',value.status.replaceAll('_',' '),'badge '+value.status),el('p',value.note));if(value.declared_validity)card.append(el('p','Declared validity now: '+value.declared_validity));}const details=el('details'),summary=el('summary','Exact evidence citations');details.append(summary);for(const c of s.citations){const source=report.sources.find(x=>x.id===c.source_id),cite=el('button',c.source_id+' '+(c.json_pointer??'signed event IDs'));cite.type='button';cite.addEventListener('click',async()=>{try{const excerpt=await request('/v1/review/evidence?purpose=investigation_review&source='+encodeURIComponent(c.source_id));if(token!==document.querySelector('#token').value)return;document.querySelector('#review-citation').hidden=false;text('#review-citation-body',JSON.stringify({...excerpt,citation:c},null,2));document.querySelector('#review-citation').scrollIntoView({block:'start'});}catch(e){text('#status',e.message);}});details.append(cite,el('p',source?.sha256??'Unknown source'));}card.append(details);cards.append(card);}
 const cases=document.querySelector('#review-cases');cases.replaceChildren();for(const c of [...report.cases,...(report.simulation?.cases??[])]){const tr=el('tr');for(const v of [c.name,c.integrity,c.authorization_at_execution,c.capture_historical,c.capture_current,c.profile_validity_now])tr.append(el('td',v));cases.append(tr);}text('#aircraft-scope',report.aircraft_comparison.scope);const gaps=document.querySelector('#aircraft-gaps');gaps.replaceChildren();for(const g of report.aircraft_comparison.gaps){const tr=el('tr');for(const v of [g.area,g.status.replaceAll('_',' '),g.next_gate])tr.append(el('td',v));gaps.append(tr);}text('#review-sources',JSON.stringify(report.sources,null,2));document.querySelector('#assurance').hidden=false;document.querySelector('#assurance').scrollIntoView({block:'start'});
 }catch(e){text('#status',e.message);document.querySelector('#status').className='error';}finally{if(token===document.querySelector('#token').value)button.disabled=false;}
});
